name: Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '11 5 * * 3'
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  analysis:
    # Scorecard publishing is available for public repositories.
    if: ${{ !github.event.repository.private }}
    uses: ossf/scorecard/.github/workflows/scorecard.yml@c395761df6afe1a69e476bc60a013a94bcbc153f # v5.5.0
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
    with:
      results_file: results.sarif
      results_format: sarif
      publish_results: true
